name: Export Game
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: 2048-godot

jobs:
  export-android:
    name: Test & Export Android
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.3
      env:
        HOME: /root
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          echo "HOME=$HOME"
          ls -la /root/.local/share/godot/export_templates/ 2>/dev/null

      - name: Run Tests
        run: |
          godot --headless -s test/run_tests.gd

      - name: Android Build
        run: |
          mkdir -v -p build/android
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "Android" "$EXPORT_DIR/android/$EXPORT_NAME.apk"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/android
